#:import LevelScreen reduction.screen.level
#:import Board reduction.component.board
#import Player reduction.component.player

<LevelScreen>:
    canvas.before:
        Color:
            rgba: 0.3, 0.3, 0.3, 1
        Rectangle:
            size: self.size

    AnchorLayout:
        RelativeLayout:
            size_hint: None, None
            size: board.size
            Board:
                id: board
            Player:
                id: player
